spring:
  application:
    name: memome-backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: openid, profile_nickname, account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            userinfo-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: sub
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  cloud.memome.backend: INFO
  org.springframework.security.oauth2: INFO
  org.springframework.web: INFO